import type { MejoraCase } from '@/lib/mejoras-model';

type SeedRow = Pick<MejoraCase, 'title' | 'need' | 'requester' | 'module' | 'area'>;

export const MEJORAS_2027_SEED: SeedRow[] = [
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Buscar producto en albaranes de cliente',
    requester: 'Santi Navarro',
    need: 'En la ficha de clientes actualmente solo se puede buscar por pedido o albarán, pero se necesita poder introducir una referencia de producto y que el sistema indique en qué albarán o albaranes aparece, ya que de lo contrario es necesario revisarlos uno a uno para localizar un producto concreto.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Vaciar referencias en Busca Plus',
    requester: 'Cristóbal',
    need: 'En Busca Plus, cuando se pega un listado de referencias en el campo de búsqueda, no existe ninguna opción para limpiar o vaciar todas las referencias de una sola vez, por lo que es necesario eliminarlas manualmente una a una, haciendo el proceso lento e ineficiente.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Traducción de Gestión al italiano',
    requester: 'Sin asignar',
    need: 'Traducción de Gestión al italiano.\n\n1. Idioma de la interfaz: ajustar toda la interfaz para que se visualice correctamente en italiano.\n\n2. Albarán – Previsualización: verificar que en la vista previa del albarán todo el contenido se muestre en italiano. Actualmente, en los packs ya aparece correctamente, pero es necesario revisar el resto.\n\n3. Productos de fabricación: no se están mostrando en italiano. Es necesario revisar y corregir esta sección.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Identificador de temporada y campañas',
    requester: 'Santi Navarro',
    need: 'Añadir un identificador en la facturación, Frees y GenWeb que permita distinguir a qué temporada corresponde cada registro (por ejemplo, 25/26 o 26/27). Además, este identificador debería facilitar el seguimiento de campañas comerciales: se sugiere implementar un campo con lista desplegable obligatorio para los EQIs que incluya opciones como Temporada 26/27, Campaña Campus, Black Friday u otras campañas relevantes. De este modo se podrá mejorar el control, análisis y trazabilidad de las acciones comerciales.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Duplicar órdenes de fabricación',
    requester: 'Juanjo',
    need: 'Poder duplicar las órdenes de fabricación.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Mínimos de producto por fecha',
    requester: 'Arturo',
    need: 'Poder marcar mínimos de producto por fecha (por ejemplo, bañadores del Mallorca, producto invierno, etc.).',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Identificar Pre-Orders B2B-B2C',
    requester: 'Laguna',
    need: 'Reservas B2B-B2C: identificar Pre-Orders efectivos.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Nombre corto de producto para reporting',
    requester: 'Alberto Antequera',
    need: 'Añadir otro campo de nombre más corto en producto para reporting: nombre 1 largo que salga en Web y nombre 2 corto para reporting.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Buscador de categorías de colectivos',
    requester: 'Samu',
    need: 'Buscador de las categorías de los colectivos, que permita escribir la categoría a mano.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Título del albarán (no “otros”)',
    requester: 'Samu',
    need: 'Título del albarán en vez de meter el producto "otros".',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Vincular albaranes y facturar frees',
    requester: 'Samu',
    need: 'Vinculación de albaranes para realizar facturación automática y así compensar frees de forma más eficiente: "Yo meto pedido de primer equipo de un club y creo el free correspondiente. Los asocio y, cuando se envía el producto, se facturan los 2 automáticamente".',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Carcasas asociadas a estampaciones',
    requester: 'Samu',
    need: 'Saber qué productos carcasas están asociados a las estampaciones',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Asociar agente a un equipo',
    requester: 'Samu',
    need: 'Campo nuevo en Gestión para asociar al Agente con un equipo (TS-Levante) para que a la hora de filtrar no haya que ir uno a uno. No por Zona porque hay albaranes que no tienen carcasas',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Colectivo: deporte, marca e idioma',
    requester: 'Cristóbal',
    need: 'añadir un campo de gestión por colectivo con deporte, marca actualizada e idioma, para facilitar a Marketing la subida de los cromos',
  },
  {
    area: 'Teamsports',
    module: 'Web',
    title: 'Personalización de prendas en web',
    requester: 'Salinero',
    need: 'Incorporar una funcionalidad de personalización de prendas similar a https://kitlocker.com/',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Calcular generado web desde precio club',
    requester: 'Cristóbal',
    need: 'Solicitar mejora IT para que, si cada gestor informa el precio club de cada pack, mediante un botón en Gestión se calcule automáticamente el generado web: (Precio Web - Precio Club) × nº de packs vendidos.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Cambiar fechas de recepción masivas',
    requester: 'Blanca',
    need: 'Solicitar a IT una mejora que permita modificar masivamente las fechas de recepción de los productos no recepcionados sin tocar las fechas de los ya recepcionados.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Descarga masiva de trackings',
    requester: 'Mario Ansini',
    need: 'Añadir como mejora en el Excel de Gestión la descarga masiva de trackings para conocer fecha de pedido, envío y recepción del cliente.',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Panel de fraccionamiento de albaranes',
    requester: 'Cristóbal',
    need: 'Panel de fraccionamiento de albaranes. Lógica: 80% liberable, 4 productos o más del albarán principal y fecha informada de salida es hoy o está retrasada',
  },
  {
    area: 'Teamsports',
    module: 'ERP',
    title: 'Fecha informada de salida editable',
    requester: 'Cristóbal',
    need: 'Revisar si la fecha informada de salida puede modificarse o ser editable. Si no, estandarizar el mensaje al club/familias para poder justificar los retrasos, dependan o no de nosotros.',
  },
];

export function buildSeedCases(): MejoraCase[] {
  return MEJORAS_2027_SEED.map((row, index) => ({
    id: `seed-2027-${String(index + 1).padStart(2, '0')}`,
    registro: index + 1,
    createdAt: '',
    requestedAt: null,
    year: 2027,
    area: row.area,
    module: row.module,
    title: row.title,
    need: row.need,
    requester: row.requester,
    addedBy: 'Cristóbal',
    channel: '',
    informedBy: '',
    channelNote: '',
    status: 'Pendiente',
    comment: '',
    attachments: [],
  }));
}
